=== dan-brown/Stammbaum/Implementierung/familytree.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT familytree (person)>

        <!ELEMENT person (inlaw?, person*)>
        <!ATTLIST person
                pid ID #REQUIRED
                forename CDATA #REQUIRED
                surname CDATA #REQUIRED
                sex (M|F) #REQUIRED
                birth_date CDATA #REQUIRED
                death_date CDATA #REQUIRED>

        <!ELEMENT inlaw EMPTY>
        <!ATTLIST inlaw pid ID #REQUIRED
                forename CDATA #REQUIRED
                surname CDATA #REQUIRED
                sex (M|F) #REQUIRED
                birth_date CDATA #REQUIRED
                death_date CDATA #REQUIRED>

=== dan-brown/Stammbaum/Implementierung/familytree2.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="inc/familytree.xsl"?>
<!DOCTYPE familytree SYSTEM "inc/familytree.dtd">
<familytree>
    <person pid="p0" forename="Abraham J." surname="Simpson" sex="M" birthDate="20.10.2015" deathDate="21.10.2015">
        <person pid="p1" forename="???" surname="" sex="F" birthDate="" deathDate="">
            <person pid="p2" forename="Herbert" surname="Powel" sex="M" birthDate="" deathDate=""/>
        </person>
        <person pid="p3" forename="Edwina" surname="" sex="F" birthDate="" deathDate="">
            <person pid="p4" forename="Abbie" surname="" sex="F" birthDate="" deathDate=""/>
        </person>
        <person pid="p5" forename="Mona" surname="Simpson" sex="F" birthDate="" deathDate="">
            <person pid="p6" forename="Homer" surname="Simpson" sex="M" birthDate="20.10.2015" deathDate="21.10.2015">
                <inlaw pid="p10" forename="Marge" surname="Simpson" sex="F" birthDate="" deathDate=""/>
                <person pid="p7" forename="Maggie" surname="Simpson" sex="F" birthDate="" deathDate=""/>
                <person pid="p8" forename="Lisa" surname="Simpson" sex="F" birthDate="" deathDate=""/>
                <person pid="p9" forename="Bart" surname="Simpson" sex="M" birthDate="" deathDate=""/>
            </person>
        </person>
    </person>
</familytree>

=== dan-brown/Stammbaum/Implementierung/familytree.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="familytree.xsl"?>
<!DOCTYPE familytree SYSTEM "familytree.dtd">
<familytree>
    <person pid="p0" forename="Opa" surname="Mustermann" sex="M" birthDate="1920-04-04"
            deathDate="2013-06-07">
        <inlaw pid="p7" forename="Oma" surname="Mustermann" sex="F" birthDate="" deathDate=""/>
        <person pid="p8" forename="Papa" surname="Mustermann" sex="M" birthDate="" deathDate="">
            <inlaw pid="p9" forename="Mama" surname="Mustermann" sex="F" birthDate="" deathDate=""/>
            <person pid="p10" forename="Daniel" surname="Brown" sex="M" birthDate="1994-09-27" deathDate=""/>
            <person pid="p2" forename="Micha" surname="Piertzik" sex="M" birthDate="1996-01-09" deathDate=""/>
            <person pid="p3" forename="Chiara" surname="Armbruster" birthDate="1996-04-29" sex="F" deathDate=""/>
            <person pid="p12" forename="Sarah" surname="Bauert" sex="F" birthDate="1995-09-23" deathDate=""/>
            <person pid="p4" forename="Schwester" surname="Mustermann" sex="F" birthDate="" deathDate="">
                <inlaw pid="p11" forename="Schwager" surname="Anders" sex="M" birthDate="" deathDate=""/>
                <person pid="p5" forename="Neffe" surname="Mustermann" sex="M" birthDate="" deathDate=""/>
                <person pid="p6" forename="Nichte" surname="Mustermann" sex="F" birthDate="" deathDate=""/>
            </person>
        </person>
    </person>
</familytree>

=== dan-brown/Stammbaum/Implementierung/familytree_2.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="familytree.xsl"?>
<!DOCTYPE familytree SYSTEM "familytree.dtd">
<familytree>
    <person pid="_0" forename="Abraham J." surname="Simpson" sex="M" birth_date="20.10.2015" death_date="21.10.2015">
        <person pid="_1" forename="???" surname="" sex="F">
            <person pid="_2" forename="Herbert" surname="Powel" sex="M"/>
        </person>
        <person pid="_3" forename="Edwina" surname="" sex="F">
            <person pid="_4" forename="Abbie" surname="" sex="F"/>
        </person>
        <person pid="_5" forename="Mona" surname="Simpson" sex="F">
            <person pid="_6" forename="Homer" surname="Simpson" sex="M" birth_date="20.10.2015" death_date="21.10.2015">
                <inlaw pid="_10" forename="Marge" surname="Simpson" sex="F"/>
                <person pid="_7" forename="Maggie" surname="Simpson" sex="F"/>
                <person pid="_8" forename="Lisa" surname="Simpson" sex="F"/>
                <person pid="_9" forename="Bart" surname="Simpson" sex="M"/>
            </person>
        </person>
    </person>
</familytree>
