=== dan-brown/Stammbaum/Implementierung/familytree relational.dtd
<?xml version="1.0" ?>
        <!ELEMENT familytree (person*, family*) >
        <!ELEMENT person EMPTY>
        <!ATTLIST person
                pid ID #REQUIRED
                forename CDATA #REQUIRED
                surname CDATA #REQUIRED
                sex (M|F) #REQUIRED
                birthdate CDATA #IMPLIED
                deathdate CDATA #IMPLIED
                spouse IDREF #IMPLIED
                >

        <!ELEMENT family EMPTY>
        <!ATTLIST family
                parent1 IDREF #REQUIRED
                parent2 IDREF #IMPLIED
                children IDREFS #REQUIRED>

=== dan-brown/Stammbaum/Implementierung/familytree relational.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="familytree relational.xsl"?>
<!DOCTYPE familytree SYSTEM "C:\Users\xce35l0\IntelliJ\Stammbaum\Implementierung\familytree relational.dtd">
<familytree>
    <person pid="0" forename="Daniel" surname="Brown" birthdate="27.09.1994" sex="M"/>
    <person pid="1" forename="Micha" surname="Piertzik" birthdate="09.01.1996" sex="M"/>
    <person pid="2" forename="Chiara" surname="Armbruster" birthdate="29.04.1996" sex="F"/>
    <person pid="3" forename="Opa" surname="Mustermann" sex="M">LOL</person>
    <person pid="4" forename="Oma" surname="Mustermann" sex="F"/>
    <person pid="5" forename="Max" surname="Mustermann" sex="M"/>
    <person pid="6" forename="Maria" surname="Mustermann" sex="F"/>
    <person pid="7" forename="Sohn" surname="Mustermann" sex="M"/>
    <family parent1="3" parent2="4" children="5">Lol</family>
    <family parent1="5" parent2="6" children="243">Lol</family>
</familytree>

=== dan-brown/Stammbaum/Implementierung/relational/familytree relational.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="familytree relational.xsl"?>
<!DOCTYPE familytree SYSTEM "familytree relational.dtd">
<familytree>
    <person pid="0" forename="Daniel" surname="Brown" birthdate="27.09.1994" male="TRUE"/>
    <person pid="1" forename="Micha" surname="Piertzik" birthdate="09.01.1996" male="TRUE"/>
    <person pid="2" forename="Chiara" surname="Armbruster" birthdate="29.04.1996" male="FALSE"/>
    <person pid="3" forename="Opa" surname="Mustermann" male="TRUE">LOL</person>
    <person pid="4" forename="Oma" surname="Mustermann" male="FALSE"/>
    <person pid="5" forename="Max" surname="Mustermann" male="TRUE"/>
    <person pid="6" forename="Maria" surname="Mustermann" male="FALSE"/>
    <person pid="7" forename="Sohn" surname="Mustermann" male="TRUE"/>
    <family parent1="3" parent2="4" children="5">Lol</family>
    <family parent1="5" parent2="6" children="243">Lol</family>
</familytree>
